Proto test
PWrInSpace/MCB_Aurora pull request #11
Opened 2023-04-11 08:38 UTC by JSiuda1

* podpięcie sd flash lory i esp now
* dodanie generatora ramek do sd
* podpięcie protobufa i komend do lory

2023-04-11 16:51 UTC, kgliwinski requested changes

2023-04-11 16:51 UTC, kgliwinski commented on components/pysd_gen/gen_pysd.c
> +        snprintf(buffer, size, "%d;%lu;%d;%f;%d;%d;%d;%d;%d;%f;%f;%d;%d;%f;%f;%f;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;\n", pysd_main.mcb.state, pysd_main.mcb.uptime, pysd_main.mcb.flight_time, p
w obydwoch jest \n

2023-04-11 16:51 UTC, kgliwinski commented on components/pysd_gen/gen_pysd.c
> +    frame_size = pysd_get_sd_frame_size(pysd_main, new_line_ending);
pysd_get_frame_size robi dokladnie to samo co pysd_create_sd_frame z jedna roznica ze zwraca dlugosc ramki, mozesz to miec w jednej funkcji i bedzie zajmowac polowe czasu

2023-04-11 16:51 UTC, kgliwinski commented on components/pysd_gen/gen_pysd.c
> +    } else {
dodatkowo zamiast robic takie potezne ify mozna strcat uzyc

2023-04-11 16:51 UTC, kgliwinski commented on components/sd_card/sd_card_config.c
> +static void on_sd_data_timer(TimerHandle_t xTimer) {
kopiuj-wklej z flash configu, proponuje zrobic oddzielny komponent do timera zamiast powielac kod

2023-04-11 16:51 UTC, kgliwinski commented on components/sys/lora_hw_config.h
tutaj prosze dodac deklaracje funkcji z lora_hw_config.c

2023-04-11 16:51 UTC, kgliwinski commented on components/utils/utils.c
> +    return 420;
🐶

2023-04-14 20:21 UTC, JSiuda1 commented on components/sys/lora_hw_config.h
Qué?

2023-04-14 20:23 UTC, JSiuda1 commented on components/sd_card/sd_card_config.c
> +static void on_sd_data_timer(TimerHandle_t xTimer) {
Obuduje timera w timer i nic się nie zmieni. A wole mieć tutaj obsługę timera który  jest związany z tym taskiem.

2023-04-14 20:24 UTC, JSiuda1 commented on components/utils/utils.c
> +    return 420;
¿Quieres

2023-04-16 17:40 UTC, kgliwinski approved these changes

2023-04-16 17:40 UTC, kgliwinski commented on components/sys/lora_hw_config.h
pasa

2023-04-16 18:10 UTC, merged